version: "3"
services:
  nginx:
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - "${LNMP_DATA}/nginx/html:/usr/share/nginx/html"
      - "/etc/localtime:/etc/localtime:ro"
      - "${LNMP_DATA}/nginx/conf:/etc/nginx"
      - "${LNMP_DATA}/nginx/log:/var/log/nginx"
    image: nginx:latest
    restart: always
  mysql:
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${LNMP_DATA}/mysql/data:/var/lib/mysql"
    image: mysql:5.7.39
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
  php-fpm7.4:
    image: php-fpm7.4:2
    container_name: php-fpm7.4
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${LNMP_DATA}/php-fpm7.4/conf:/usr/local/etc"
      - "${LNMP_DATA}/php-fpm7.4/logs:/usr/local/var/log"
      - "${LNMP_DATA}/php-fpm7.4/logs:/usr/local/var/run"
      - "${LNMP_DATA}/nginx/html:/var/www/html"
    restart: always
  redis:
    container_name: redis
    privileged: true
    ports:
      - "6379:6379"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${LNMP_DATA}/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf"
      - "${LNMP_DATA}/redis/data:/data"
      - "${LNMP_DATA}/redis/logs:/logs"
    image: redis:latest
    restart: always
    environment:
      - TZ="Asia/Shanghai"
    command: ["redis-server","/usr/local/etc/redis/redis.conf","--appendonly yes"]